/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React, { useRef } from 'react';

export default function Tree() {
  const group = useRef();
  //   @ts-ignore
  const { nodes, materials } = useGLTF('/tree.gltf');
  return (
    <group ref={group} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.Trunk1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials.Leaf1}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/tree.gltf');
